a=(1,2,3,4,5)
print("tuple:",a)
print("we can't modify the tuple so we casting tuple into list now we can modify")
b=list(a)
print("casting:",b)
b.append(6)
print(b)
c=tuple(b)
print("recasting:",c)
